#include "TM4C123.h"
#include "gpio.h"

int main(void) {
	


	GPIO_Init(PORTF_ID);
	GPIO_SetPinDirection(PORTF_APB_BASE,PIN_ID1,PIN_OUTPUT);
	GPIO_SetPinDirection(PORTF_APB_BASE,PIN_ID0,PIN_INPUT);
	GPIO_SetPinDirection(PORTF_APB_BASE,PIN_ID4,PIN_INPUT);
	GPIO_SetPadConfig(PORTF_APB_BASE,PIN_ID0,GPIO_PIN_STRENGTH_8MA,GPIO_PIN_TYPE_PUR);
	GPIO_SetPadConfig(PORTF_APB_BASE,PIN_ID4,GPIO_PIN_STRENGTH_8MA,GPIO_PIN_TYPE_PUR);
	
	
	while(1) {
		
		if((GPIO_ReadPin(PORTF_APB_BASE,PIN_ID0)) == LOGIC_LOW)
			GPIO_WritePin(PORTF_APB_BASE,PIN_ID1,LOGIC_HIGH);
		else if((GPIO_ReadPin(PORTF_APB_BASE,PIN_ID4)) == LOGIC_LOW)
			GPIO_WritePin(PORTF_APB_BASE,PIN_ID1,LOGIC_LOW);
		else {
			GPIO_TogglePin(PORTF_APB_BASE,PIN_ID1);
			for(volatile int i = 0 ; i<1000000;i++);
		}
		
	}
	
}


